version: '2'

services:
 web1:
  image: amanu/php56-apache
  volumes:
   - ./ABD_STORE:/var/www/html/
  ports:
   - "8001:80"
  links:
   - "db1:sql"

 db1:
  build: .
  container_name: sql
  ports:
   - "3308:3308"
  volumes:
   - db_data:/var/lib/mysql
  restart: always
  environment:
   MYSQL_DATABASE: muhammad_abdullah
   MYSQL_ROOT_PASSWORD: root

volumes:
 db_data:
